import { Dimensions, StyleSheet } from "react-native";

const { height } = Dimensions.get("window");


const styles = StyleSheet.create({

    container:{backgroundColor: '#EFEFEF'},
    flex:{flex:1},
    paddinghorizontal:{paddingHorizontal:15},
    avatarframe:{backgroundColor:"#fff", padding:15, borderRadius:20},
    marginBottom1:{marginBottom:15},
    avatarheight:{width: 65,height: 65},
    empavatar:{borderRadius:15},
    status:{color: '#000',fontSize: 18,fontWeight: '500'},
    rowitem:{flexDirection:"row",gap:15},
    gap:{gap:15},
    color:{color:"#646464"},
    width70:{ width:"70%"},
    centeralign:{alignItems: 'center',justifyContent: 'center'},
    margintop:{marginTop:15},
    locationtxt:{fontSize:16,fontWeight:'500'},
    employeecard:{flex: 1,backgroundColor: 'rgba(0,0,0,0.5)',justifyContent: 'center',alignItems: 'center',padding: 20},
    statusframe:{backgroundColor:'#fff',padding:20,borderRadius:30},
    width100:{ width:"100%"},
    plantxt:{fontSize:16, fontWeight:"500"},
    bellicon:{height: 50, width: 50},
    iconframe:{backgroundColor: "#8E6BDD",borderRadius: 30},
    cross:{position:'absolute',top:15,right:15,backgroundColor:'#c1c1c1',borderRadius:'50%'},
    mtop:{marginTop:"auto"},
    floatingaddicon:{position:'absolute',bottom:60,right:30,width:60},
    gap5:{gap:5},
    width60:{width:'60%'},
    colorred:{color:'#f00'},
    paddingbottom:{paddingBottom: 15},
    clientbanner:{ width: "100%", height: 200, borderRadius: 10},
    width48:{width:'48%'},
    dashboardcontainer:{flex: 1, backgroundColor: "#8E6BDD",height:"50%"},
    dashboardframe:{flex: 1,backgroundColor:"#EFEFEF",borderTopLeftRadius:40,borderTopRightRadius:40,padding:15,paddingBottom:0},
    clientbox:{ flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center" },
    clientframe:{ backgroundColor: "#fff", margin: 20, borderRadius: 30, padding: 20},
    employeeprofile:{height: 120, width: 120,borderRadius: 20},
    rightalign:{marginLeft: 'auto'},
    row:{flexDirection:'row', gap:5},
    colorgray:{color:'#999'},
    image:{ height: 150, width: 230, alignSelf: "center" },
    width65:{width:"65%"},
    width80:{ width:"80%"},
    marginVertical:{marginVertical:20},
    map:{height:height* 0.3,borderRadius:30,overflow:"hidden",borderColor:'#f9f9f9',borderWidth:2},
    locationicon:{position:"absolute",top:60,right:11,padding:6,backgroundColor:"rgba(255,255,255,0.7)",borderRadius:2},
    text:{flex: 1,color: '#646464',fontSize: 18,fontWeight:'500'},
    inputcard:{ flex: 1, justifyContent: "center"},
    searchcard:{backgroundColor:'#fff', paddingVertical:5,paddingHorizontal:10,borderRadius:30,borderColor:'#d9d9d9',borderWidth:2,justifyContent:'center'},
    statusbg:{borderRadius:50,paddingVertical:3,paddingHorizontal:10,alignSelf:"flex-start",position:"absolute",right:0},
    iconbox:{left: 65,top: -55},
    logoimg:{ width: 84, height: 48 },
    header:{ color:'#8E6BDD',fontSize:30,fontWeight:'bold'},
    marginBottom:{marginBottom:50},
    fontweight:{fontWeight:'bold'},
    btn:{backgroundColor:"#8E6BDD",height:50,borderRadius:20,justifyContent:"center",alignItems:"center",width:"100%",alignSelf:"center"},
    disabledBtn:{backgroundColor:"#d9d9d9",},
    btnText:{fontSize:18,fontWeight:"bold",color:"#fff",paddingBottom:5},
    profileavatar:{borderRadius:20,borderColor:'#fff',borderWidth:4,marginTop:10},
    txt:{color:'#fff',fontSize:26,fontWeight:'bold'},
    quot:{color:'#E9E9E9',fontSize:16,fontWeight:'bold'},
    reddot:{position:"absolute",top:-2,right:-2,width:15,height:15,borderRadius:"50%",backgroundColor:"#f00"},
    card:{width:"48%",backgroundColor:'#fff',borderRadius: 30,padding:20},
    cardtxt:{color:'#646464',fontSize:18,fontWeight:'500'},
    cardnum:{color:'#000',fontSize:30,marginTop:7,fontWeight:'bold',textAlign:'center'},
    bigcard:{padding:20,backgroundColor:'#fff',borderRadius:20,alignItems:'center',justifyContent:'center'},
    cameraicon:{height: 70,width: 70},
    removeButton:{position:"absolute",top:-5,right:-5,backgroundColor:"#8E6BDD",borderRadius:"50%",padding:2},
    icon:{marginTop:13},
    box:{backgroundColor:"#fff",paddingHorizontal:20,borderRadius:20,flexDirection:"row",alignItems:"center"},
    profilecard:{backgroundColor:'#fff',borderRadius:20,padding:15},
    label:{fontSize:16,fontWeight:'500',color:'#646464',paddingLeft:10},
    profiletext:{color:'#000',fontSize:18,fontWeight:'500',paddingLeft:10},
    padding10:{padding:10},
    padding15:{padding:15},
    h50:{height:50},
    h60:{height:60},    
    leftalign:{marginRight:'auto'},
    round:{borderRadius:10,bottom:15},    
    profile:{height:150,width:150,borderRadius:40,borderColor:'#fff',borderWidth:6},
    centerContainer: { position: 'absolute', left: 0, right: 0, alignItems: 'center', padding: 15 },
    statusbtn:{width:"30%", padding:10,alignItems:'center', borderRadius:20, backgroundColor:'#fff'},
    crossicon:{position: "absolute",bottom:10},
   
});

export default styles;